### ISSUE TITLE
Cant install on a VPS, because setup console needs a local graphical browser

### ISSUE THREAD

**Issue by c-cesar** [EmissarySocial/emissary#357]
I tried to install on a VPS, but had to install on my local machine, because the setup console tries to open a graphical browser, unavailable on the VPS, and can't access the setup console trough the reverse proxy. Tried to use Links2 and Lynx, on the VPS but none can render the setup page correctly due to JS.

Allowing remote access to setup console can be quite dangerous, as it don't require credentials, and it's not a not a one time thing, like Wordpress install procedure. Maybe, the best solution is to create the first admin user outside setup console and lock it behind authentication to allow remote access to it.

**Comment by benpate** [comment]
Howdy @c-cesar ~ thanks so much for checking out Emissary!

The quickstart guide assumes you're testing on your local device, and I can see how you'd run into trouble using `--setup` mode on a VPS.  But there are several options for you to move forward, so you shouldn't be stuck for long.

1) The simplest solution is to **use your own machine as a management console**. I have several sites running on a production Emissary install on Digital Ocean, and frequently log in to make changes from my own desktop.  Try something like this: `go run server.go --setup --config:mongodb://[MONGO-DB-CONNECT-STRING]`.  This will let you configure your production sites you want to use from the setup console.  

Then on your VPS, you'll do something similar, running Emissary in regular server mode using that MongoDB configuration database.  `go run server.go --config:mongodb://[MONGO-DB-CONNECT-STRING]` (note: WITHOUT the `--setup` option)

2) I prefer to bootstrap Emissary using a mongodb database, but you can also **start up using a JSON config file**.  You could hand-code the JSON config, then upload it to your VPS.  The command to run on your VPS would be: `go run server.go --config:file://[PATH-TO-JSON-CONFIGURATION]`.  You could also point to this file using environment variables, if that's easier.

Hopefully this makes sense?  Let me know if you're having trouble.. I'm very interested in helping others to get Emissary running in their own environments.

**Comment by benpate** [comment]
I wanted to address security in a separate message.  Yes, any kind of setup console could pose a security risk.  I put a lot of thought into this, and hopefully I can address your concerns.

Once you're ready to turn Emissary on to the public, you run in server mode, without the `--setup` option.  In this mode, Emissary doesn't even have routes to the setup tool, and won't perform any setup actions.

So, the setup console doesn't have a password because it's not supposed to be running on a publicly available server.  I see it running only on a private machine, and on an "as-needed" basis.  The example above follows this.  On my local, secured machine, I can fire up the Emissary setup console because I have 1) the credentials to access the production database, and 2) am running on a network that's allowed to connect to the database.  The same would be true if I was using a network file share to access a configuration file.

In the end, the security config file (or db record) is what matters most.  Anyone who can access this file has full control over your server, so access to it must be tightly controlled.

Does this answer your question?

**Comment by benpate** [comment]
okay to close this?
