### ISSUE TITLE
Double inclusion of header

### ISSUE THREAD

**Issue by andrewmoise** [EmissarySocial/emissary#360]
Hey there -- so in looking at the HTML generated for some pages on the setup server, it looks like the header is included twice:

* It's explicitly included from files like `_embed/setup/index.html` via `{{template "_header.html" "index"}}`
* It's added in `handler/setup_server.go` by `SetupPageGet()` if `useWrapper` is set

I solved the problem for me by just removing this code from `SetupPageGet()` entirely:

```
               if useWrapper {
                       if err := templates.ExecuteTemplate(ctx.Response().Writer, "_header.html", config); err != nil {
                               derp.Report(builder.WrapInlineError(ctx.Response(), derp.Wrap(err, "setup.getIndex", "Error building index page")))
                       }
               }
```

... but I didn't understand the issues involved fully, so maybe it'd be better to remove it from the template side instead, or maybe there's a more sophisticated fix needed. But in any case, removing that code made it work for me on the limited number of pages I checked.

**Comment by benpate** [comment]
Hey, thank you.  I'm looking at this now.

**Comment by benpate** [comment]
It looks like you're exactly right.  I have no excuse.  I probably just missed this when I was moving some things around, and then didn't notice it because it didn't show up in the UI.

We can also remove the "footer" too, for the same reasons, that simplifies this function even further.

I've just [pushed a fix to dev](https://github.com/EmissarySocial/emissary/commit/00042750ad01b8c9d3ac9d05a38e394ecb32d4b7) that'll get included when I do another release to main.  This should be pretty soon, because I've stacked up a bunch of changes since the last one :)

**Comment by benpate** [comment]
okay to close this?

**Comment by andrewmoise** [comment]
Yeah, fine for me
